ANDROID_FORUM_URL = "https://androidforums.com/"
GSMARENA_URL = "https://www.gsmarena.com/"
ANDROID_PIT_FORUM_URL = "https://www.androidpit.com"
ANDROID_FORUM_STRING = "androidforums"
GSMARRENS_STRING = "gsmarena"
ANDROID_PIT_FORUM_STRING = "androidpit"
